// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (id, created_at, updated_at, name, user_id)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3
)
RETURNING id, created_at, updated_at, name, user_id
`

type CreateChatParams struct {
	ID     uuid.UUID
	Name   string
	UserID uuid.UUID
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, arg.ID, arg.Name, arg.UserID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.UserID,
	)
	return i, err
}

const deleteChats = `-- name: DeleteChats :exec
DELETE FROM chats
`

func (q *Queries) DeleteChats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteChats)
	return err
}

const getChat = `-- name: GetChat :one
SELECT id, created_at, updated_at, name, user_id FROM chats
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetChat(ctx context.Context, name string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, name)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.UserID,
	)
	return i, err
}
